apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80          # Port exposed within the cluster
      targetPort: 8080  # Port on the container
      nodePort: 30080   # Port exposed on each node (30000-32767)
      protocol: TCP
      name: http